### ISSUE TITLE
retirar arquivos compilados do repositorio

### ISSUE THREAD

**Issue by mrlcosta** [KayleKylian/conversor-unidades#24]
pessoal, vamos adicionar a pasta output ao arquivo do gitignore!
ele pode ser compilado on demand sempre que necessário.

**Comment by KayleKylian** [comment]
O próprio arquivo .gitignore já exclui a pasta output, pelo fato de que dentro dela existem apenas executáveis .exe, que entram em suas exceções, então não é necessário.
Para se perceber isso, basta checar o repositório, pois em momento algum apresenta a pasta.

**Comment by mrlcosta** [comment]
Estou reabrindo a issue novamente.
Nem todos os integrantes utilizam windows e nem todas as extensões e diretórios estão cobertos pelo .ignore padrão.

Reabrindo issue. 
O PR irá fechar a issue, quando for mergeado.

**Comment by mrlcosta** [comment]
<img width="261" alt="Captura de Tela 2024-12-22 às 15 08 11" src="https://github.com/user-attachments/assets/b958b83e-d1d6-41a2-b03e-b6bfcfb091b9" />

segue imagem de exemplo, mostrando o arquivo da pasta sendo trackeado.
